export const appdata = [
    {
        id: 1,
        greet: "Hello Travels",
        contact: "Contact 1",
        city: "City 1",
        state: "State 1",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 1",
        designation: "Designation 1",
        email: "contact1@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 2,
        greet: "Hello Travels",
        contact: "Contact 2",
        city: "City 2",
        state: "State 2",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 2",
        designation: "Designation 2",
        email: "contact2@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 3,
        greet: "Hello Travels",
        contact: "Contact 3",
        city: "City 3",
        state: "State 3",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 3",
        designation: "Designation 3",
        email: "contact3@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 4,
        greet: "Hello Travels",
        contact: "Contact 4",
        city: "City 4",
        state: "State 4",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 4",
        designation: "Designation 4",
        email: "contact4@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 5,
        greet: "Hello Travels",
        contact: "Contact 5",
        city: "City 5",
        state: "State 5",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 5",
        designation: "Designation 5",
        email: "contact5@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 6,
        greet: "Hello Travels",
        contact: "Contact 6",
        city: "City 6",
        state: "State 6",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 6",
        designation: "Designation 6",
        email: "contact6@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 7,
        greet: "Hello Travels",
        contact: "Contact 7",
        city: "City 7",
        state: "State 7",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 7",
        designation: "Designation 7",
        email: "contact7@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 8,
        greet: "Hello Travels",
        contact: "Contact 8",
        city: "City 8",
        state: "State 8",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 8",
        designation: "Designation 8",
        email: "contact8@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 9,
        greet: "Hello Travels",
        contact: "Contact 9",
        city: "City 9",
        state: "State 9",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 9",
        designation: "Designation 9",
        email: "contact9@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 10,
        greet: "Hello Travels",
        contact: "Contact 10",
        city: "City 10",
        state: "State 10",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 10",
        designation: "Designation 10",
        email: "contact10@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 11,
        greet: "Hello Travels",
        contact: "Contact 11",
        city: "City 11",
        state: "State 11",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 11",
        designation: "Designation 11",
        email: "contact11@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 12,
        greet: "Hello Travels",
        contact: "Contact 12",
        city: "City 12",
        state: "State 12",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 12",
        designation: "Designation 12",
        email: "contact12@gmail.com",
        phone: 874685465465,
        country: "India"
    },
    {
        id: 13,
        greet: "Hello Travels",
        contact: "Contact 13",
        city: "City 13",
        state: "State 13",
        desc: "This is Description.This is Description.This is Description.This is Description.This is Description.This is Description.",
        address: "Address 13",
        designation: "Designation 13",
        email: "contact13@gmail.com",
        phone: 874685465465,
        country: "India"
    },
]